### ISSUE TITLE
JSON Format Error

### ISSUE THREAD

**Issue by earlpeterg** [dmaasland/lastpass-authenticator-export#1]
In my case, mfa_data returned with the following data at the end of the export.

`{"accounts":[{"` ... `"deviceId":"6d241bc0-1e5d-4a3b-8c33-b3453c92d26e"}\x06\x06\x06\x06\x06\x06`

Causing this error:

```
Traceback (most recent call last):
  File "d:/Documents/Personal/PythonTestingArea/lastpass-authenticator-export.py", line 178, in <module>
    main()
  File "d:/Documents/Personal/PythonTestingArea/lastpass-authenticator-export.py", line 173, in main
    mfa_data = decrypt_user_data(user_data, key)
  File "d:/Documents/Personal/PythonTestingArea/lastpass-authenticator-export.py", line 109, in decrypt_user_data
    f.write(plaintext)
TypeError: write() argument must be str, not bytes
```

I got it to work but I haven't fixed the script properly as I hard coded the values just to get my export.

**Comment by dmaasland** [comment]
That does look an awful lot like padding. I'll check if I can fix it later today. Thanks!

**Comment by dmaasland** [comment]
Could you try it now with the latest version?

**Comment by earlpeterg** [comment]
It's now working properly. Thanks a lot and have a nice day!
