### ISSUE TITLE
KeyError: 'userData'

### ISSUE THREAD

**Issue by ricciocri** [dmaasland/lastpass-authenticator-export#19]
Just tried to use the docker and I got this error :

> Traceback (most recent call last):
>   File "//lastpass-authenticator-export.py", line 212, in <module>
>     main()
>   File "//lastpass-authenticator-export.py", line 206, in main
>     user_data = get_mfa_backup(session, csrf)
>   File "//lastpass-authenticator-export.py", line 110, in get_mfa_backup
>     return r.json()['userData']
> KeyError: 'userData'

**Comment by gasjur** [comment]
I got the same error aswell, tried with different pyhton version
